training:
        corpus: europarl-v7
        pair: es-en
        sl: es
        tl: en
        data: /home/venkat/Apertium/apertium-en-es
        lex_tools: /home/venkat/Apertium/apertium-lex-tools
        scripts: /home/venkat/Apertium/apertium-lex-tools/scripts
        mosesdecoder: /home/venkat/Apertium/mosesdecoder/scripts/training
        lines: 1000
learning:
        bin_dir: /home/venkat/Apertium/mgiza/mgizapp/bin
        lm: /home/venkat/Apertium/lm/train.lm
        run_mle: True
        run_mer: True
        mle_crisphold: 1.5
        mer_min: 1
